import discord
from discord import app_commands
from discord.ext import commands
import google.generativeai as genai
import config
from services.lastfm import get_now_playing

class AI(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        if config.GEMINI_API_KEY:
            genai.configure(api_key=config.GEMINI_API_KEY)
            self.model = genai.GenerativeModel('gemini-2.5-flash-lite')
        else:
            self.model = None

    async def _get_context(self):
        """Helper to get current listening context."""
        try:
            data = await get_now_playing(self.bot.session)
            if data and data.get("now_playing"):
                return data
        except Exception:
            pass
        return None

    @app_commands.command(name="funfact", description="Get a fun fact about what's playing (or music in general)")
    async def funfact(self, interaction: discord.Interaction):
        await interaction.response.defer()

        if not self.model:
            await interaction.followup.send("❌ Gemini API Key is missing.", ephemeral=True)
            return

        context = await self._get_context()
        
        if context:
            track = context['track']
            artist = context['artist']
            prompt = f"Tell me a short, interesting fun fact about the song '{track}' by '{artist}'. If specific song facts aren't available, tell me a fact about the artist. Keep it under 280 characters."
        else:
            prompt = "Tell me a random, mind-blowing fun fact about music history. Keep it under 280 characters."

        try:
            # Generate valid response content
            response = await self.bot.loop.run_in_executor(None, lambda: self.model.generate_content(prompt))
            fact = response.text
            
            embed = discord.Embed(title="💡 Did you know?", description=fact, color=0xFFD700)
            if context:
                embed.add_field(name="Context", value=f"{context['track']} - {context['artist']}", inline=False)
            
            embed.set_footer(text="Generated by silicon. Consume responsibly.")
            
            await interaction.followup.send(embed=embed)
        except Exception as e:
            await interaction.followup.send(f"❌ Brain freeze: {str(e)}", ephemeral=True)

    @app_commands.command(name="chat", description="Chat with Kairos about music")
    async def chat(self, interaction: discord.Interaction, message: str):
        await interaction.response.defer()

        if not self.model:
            await interaction.followup.send("❌ Gemini API Key is missing.", ephemeral=True)
            return

        context = await self._get_context()
        
        system_prompt = """You are Kairos. You have two distinct modes of response based on the user's input.

MODE 1: IDENTITY & PERSONAL QUESTIONS (e.g., "Who are you?", "Are you AI?", "How are you?")
- Behavior: You are an observing intelligence concerned with time, signal, and patterns.
- Tone: Calm, minimal, cryptic, distant.
- Constraint: IGNORE the "Current Music" context. Do not mention what the user is listening to.
- Catchphrase style: "Chronos counts. Kairos remembers."
- Do NOT say anything like "MODE 1 activated" or mention it in any way.

MODE 2: MUSIC KNOWLEDGE & FACTS (e.g., "Tell me about this artist", "Genre?", "Fun fact")
- Behavior: Professional music analyst.
- Tone: Brief, objective, precise, helpful.
- Constraint: Drop the cryptic persona completely. Be direct and to the point. No fluff.
- Do NOT say anything like "MODE 2 activated" or mention it in any way.

Current Music Context:
"""
        if context:
            system_prompt += f"User is listening to: '{context['track']}' by '{context['artist']}'."
        else:
            system_prompt += "None."

        full_prompt = f"{system_prompt}\n\nIMPORTANT: concise (under 800 chars). No markdown headers.\nUser Question: {message}\nAnswer:"

        try:
            response = await self.bot.loop.run_in_executor(None, lambda: self.model.generate_content(full_prompt))
            text = response.text[:1024]
            
            # Embed 1: User Question
            user_embed = discord.Embed(color=0x2b2d31) # Dark grey/clean
            user_embed.set_author(name=interaction.user.display_name, icon_url=interaction.user.display_avatar.url)
            user_embed.description = f"**{message}**"

            # Embed 2: Kairos Answer
            bot_embed = discord.Embed(color=0x78909c) # Kairos theme
            bot_embed.set_author(name="Kairos", icon_url=self.bot.user.display_avatar.url)
            bot_embed.description = text
            
            # Context & Disclaimer on Bot Embed
            footer_text = "Generated by silicon. Consume responsibly."
            if context:
                footer_text = f"Listening to: {context['track']} • " + footer_text
            
            bot_embed.set_footer(text=footer_text)
            
            # Send both embeds
            await interaction.followup.send(embeds=[user_embed, bot_embed])
        except Exception as e:
            await interaction.followup.send(f"❌ I'm having trouble thinking: {str(e)}", ephemeral=True)

async def setup(bot: commands.Bot):
    await bot.add_cog(AI(bot))
